BookCave/Models/EntityModels/Book.cs
using System.Collections.Generic;   

namespace BookCave.Models.EntityModels
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public List<BookIdItem> AuthorBookIdList { get; set; }
        public string Publisher { get; set; }
        public int YearPublished { get; set; }
        public double Price { get; set; }
        public int Pages { get; set; }
        public List<CategoryIdItem> CategoryIdList { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public double Rating { get; set; }
        public int Discount { get; set; }
        public int AuthorId { get; set; }
        public int CategoryId { get; set;}
    }
}

BookCave/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BookCave.Models;
using BookCave.Services;

namespace BookCave.Controllers
{
    public class AuthorController : Controller
    {
        private AuthorService _authorService;
        
        public AuthorController()
        {
            _authorService = new AuthorService();
        }
        [HttpGet]
        public IActionResult Index()
        {
            var authors = _authorService.GetAllAuthors();
            return View(authors);
        }
        [HttpPost]
        public IActionResult Index(string SearchString)
        {
            ViewBag.Title = "Leit";
            var authors = _authorService.GetAuthorsByName(SearchString);
            return View(authors);
        }
        public IActionResult GetAuthors()
        {
            var authors = _authorService.GetAllAuthors();
            return Json(authors);
        }
        public IActionResult Details(int id)
        {
            var authors = _authorService.GetDetailsAuthor(id);
            ViewBag.Title = authors.Name;
            return View(authors);
        }
    }
}

BookCave/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BookCave.Models;
using BookCave.Services;
using BookCave.Models.EntityModels;

namespace BookCave.Controllers
{
    
    public class BookController : Controller
    {
        private BookService _bookService;
        private AccountService _accountService;

        public BookController()
        {
            _bookService = new BookService();
            _accountService = new AccountService();
        }
        [HttpGet]
        public IActionResult Index()
        {
            var books = _bookService.GetAllBooks();
            return View(books);
        }
        [HttpPost]
        public IActionResult Search(string SearchBy, string SearchString)
        {
            var books = _bookService.GetBooksBySearch(SearchBy, SearchString);
            ViewBag.Title = "Leit";
            if(books.Equals(0))
            {
                return RedirectToAction("NothingFound");
            }
            return View(books);
        }

        public IActionResult NothingFound()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            ViewBag.Title = "Nánar";
            var books = _bookService.GetBookDetails(id);
            if(books == null)
            {
                return Content("Not Found");
            }
            ViewBag.Title = books.Title;
            return View(books);
        }
        [HttpPost]
        public IActionResult Details(int id, string comment, int rating)
        {
            var newComment = new Comment
            {
                BookComment = comment,
                Rating = rating,
                BookId = id
                //user
            };

            if(ModelState.IsValid)
            {
                _accountService.AddComment(newComment);
            }

            //var books = _bookService.GetBookDetails(id);
            
            return RedirectToAction("Details");
        }
        
    }
}

BookCave/Controllers/CategoryController.cs
using BookCave.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookCave.Controllers
{
    public class CategoryController : Controller
    {
        private CategoryService _categorieService;

        public CategoryController() 
        {
            _categorieService = new CategoryService();
        }

        public IActionResult Index()
        {
            var categories = _categorieService.GetAllCategories();
            return View(categories);
        }
        public IActionResult GetCategories()
        {
            var categories = _categorieService.GetAllCategories();
            return Json(categories);
        }

        public IActionResult Details(int id)
        {
            var name = _categorieService.GetCategory(id).Name;
            ViewBag.Category = name;
            ViewBag.Title = name;

            var result = _categorieService.GetCategoryDetails(id);

            if(result == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(result);
            }
        }
    }
}

BookCave/Views/Book/Details.cshtml
@model BookCave.Models.ViewModels.BookDetailViewModel
@using Microsoft.AspNetCore.Identity
<h1>@Model.Title</h1>
<div class="jumbotron">
    <div>
        <p>Einkunn: @Model.Rating</p>
        <img src="@Model.Image"  height="200" width="120" /><br>
        <p>Eftir: 
            @foreach(var a in @Model.AuthorList)
            {
                <a asp-controller="Author" asp-action="Details" asp-route-id="@a.Id">@a.Name</a>
            }
        </p>
        <p>Flokkar: 
            @foreach(var c in @Model.CategoryList)
            {
                <a asp-controller="Category" asp-action="Details" asp-route-id="@c.Id">@c.Name</a> 
            }
        </p>
        <p>Verð: @Model.Price $</p>
        <p>Lýsing: @Model.Description</p>
        <p>Blaðsíðutal: @Model.Pages</p>
    </div>
    @if(User.IsInRole("User"))
    {
        <div>
            <input type="button" class="btn btn-info" value="Setja í körfu" onclick="addToCart(@Model.Id)">
        </div>
    }
    else
    {
        <div>
            <input type="button" class="btn btn-info" value="Setja í körfu" onclick="notAdded()">
        </div>
    }
</div>
@if(User.IsInRole("User"))
{
<h3>Skrifa umsögn</h3>
<div class="jumbotron">
    <form method="POST" asp-controller="Book" asp-action="Details">
        <div class="form-group">
            <input type="text" for="Comment" name="Comment" class="form-control">
        </div>
        <p>Einkunn</p>
        <div class="btn-group btn-warning" data-toggle="buttons">
            <label class="btn btn-secondary active">
                <input type="radio" name="Rating" value="1" autocomplete="off" checked>
                <span class="glyphicon glyphicon-star"></span>
            </label>
            <label class="btn btn-secondary">
                <input type="radio" name="Rating" value="2" autocomplete="off">
                <span class="glyphicon glyphicon-star"></span>
            </label>
            <label class="btn btn-secondary">
                <input type="radio" name="Rating" value="3" autocomplete="off">
                <span class="glyphicon glyphicon-star"></span>
            </label>
            <label class="btn btn-secondary">
                <input type="radio" name="Rating" value="4" autocomplete="off">
                <span class="glyphicon glyphicon-star"></span>
            </label>
            <label class="btn btn-secondary">
                <input type="radio" name="Rating" value="5" autocomplete="off">
                <span class="glyphicon glyphicon-star"></span>
            </label>
        </div><br><br>
        <button type="submit" class="btn btn-default">Skrá umsögn</button>
    </form>
</div>
}
<h3>Umsagnir</h3>
<div class="jumbotron">
    <h4>Meðaltal einkunna frá notendum: @Model.UserAvgRating</h4>
    @foreach(var c in @Model.BookComments)
    {
        <div>
            <p>Einkunn: @c.Rating </p>
            <p>Umsögn: @c.BookComment</p> <br>
        </div>
    }
</div>

BookCave/Views/Book/Index.cshtml
@model List<BookCave.Models.ViewModels.BookListViewModel>
<h1>Bækur</h1>
        <li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Raða eftir <span class="caret"></span></a>
<ul class="dropdown-menu" id="list-menu">
                <li><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-id="Stafrodsrod">Stafrófsröð</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-id="VerdLH">Verð lægra til hærra</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-id="VerdHL">Verð hærra til lægra</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-id="Einkunn">Einkunn</a></li>
                </ul>
        </li>
    <div class="container">
    <div class="row">
        @foreach(var book in @Model)
        {
            <div class="col-lg-2 cl-md-2 col-sm-3 col-xs-6 text-center">
                <p><a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id"><img src="@book.Image" height="200" width="120"/></a></p>
               <a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id">@book.Title</a><br>
                @book.Price $
            </div>
        }
    </div>
</div>

<!-- Gamla htmlið
<div>
<ul>
    @foreach(var book in @Model)
    {
        <li class="list-inline-item">
            <img src="@book.Image" height="100" width="60" /><br>
            @book.Title<br>
            @book.Price $
        </li>
    }
  </ul>
</div>
//-->

BookCave/Views/Book/NothingFound.cshtml
<h2>Ekkert fannst</h2>

<p>Því miður skilaði þessi leit engu, ef þú ert viss um að leitarstrengurinn er réttur eigum við trúlega bókina ekki til.</p>

BookCave/Views/Book/Search.cshtml
@model List<BookCave.Models.ViewModels.BookListViewModel>
<h1>Leitarniðurstöður</h1>

<div class="container">
    <div class="row"></div>
        @foreach(var book in @Model)
        {
            <div class="col-lg-2 cl-md-2 col-sm-3 col-xs-6 text-center">
                <p><a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id"><img src="@book.Image" height="200" width="120"/></a></p>
                <a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id">@book.Title</a><br>
                @book.Price $
            </div>
        }
    </div>
</div>